const fs=require('node:fs'), path=require('node:path'), vm=require('node:vm'), assert=require('node:assert/strict');
process.env.TZ='America/Sao_Paulo';
const root=path.resolve(__dirname,'..'), ctx=vm.createContext({Date,Intl,console});
for(const file of ['data.js','metrics.js','room-search.js','report-details.js']) vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const M=ctx.SIPAE_METRICS, find=ctx.SIPAE_ROOM_SEARCH.search, collect=ctx.SIPAE_REPORT_DETAILS.collect;
const now=new Date('2026-09-11T12:00:00-03:00'), results=[];
function check(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function setup(){const data=ctx.SIPAE_DATA.create();data.allocations=[];data.requests=[];data.externalReservations=[];data.rooms.forEach(r=>r.createdDate='2026-01-01');const q={date:'2026-10-05',teacherId:'t4',classId:'c3',disciplineId:data.teacherSubjects.find(s=>s.teacherId==='t4').id,duration:2,resources:[]};return{data,q};}
function search(data,q,role='docente'){return find(data,M,q,role,now);}
check('Busca na unidade respeita capacidade, recursos e turno sem alterar dados',()=>{const{data,q}=setup();q.resources=['Computadores','Projetor'];const before=JSON.stringify(data);const r=search(data,q);assert.equal(r.error,'');assert.ok(r.rooms.length);for(const{room,slots}of r.rooms){assert.equal(room.areaId,'unidade');assert.ok(room.capacity>=18);assert.ok(room.resources.includes('Computadores')&&room.resources.includes('Projetor'));for(const s of slots){assert.ok(s.start>=13&&s.end<=17);assert.equal(s.end-s.start,2);assert.equal(M.validateBooking(data,s),null);}}assert.equal(JSON.stringify(data),before);});
check('Turma de 30 alunos elimina salas pequenas',()=>{const{data,q}=setup();q.classId='c1';const r=search(data,q);assert.ok(r.rooms.length);assert.ok(r.rooms.every(x=>x.room.capacity>=30));});
check('Manutenção e dias sem funcionamento ficam fora da busca',()=>{const{data,q}=setup();data.rooms.forEach(r=>r.status='manutencao');assert.equal(search(data,q).rooms.length,0);data.rooms.forEach(r=>r.status='ativo');q.date='2026-10-04';assert.equal(search(data,q).rooms.length,0);});
check('Reserva em outra sala do docente bloqueia sobreposição e permite horário adjacente',()=>{const{data,q}=setup();data.allocations.push({...q,roomId:'r1',status:'confirmada',start:13,end:15,areaId:'unidade',shift:'tarde'});const r=search(data,q);assert.ok(r.rooms.length);assert.ok(r.rooms.every(x=>x.slots.length===1&&x.slots[0].start===15));});
check('Reserva da turma com outro docente bloqueia sobreposição',()=>{const{data,q}=setup();data.allocations.push({...q,teacherId:'t1',roomId:'r1',status:'confirmada',start:13,end:17,areaId:'unidade',shift:'tarde'});assert.equal(search(data,q).rooms.length,0);});
check('Evento externo confirmado bloqueia só a sala e libera intervalo adjacente',()=>{const{data,q}=setup();data.externalReservations.push({id:'e-test',date:q.date,roomId:'r3',status:'aprovada',start:13,end:15});const r=search(data,q);assert.equal(r.rooms.find(x=>x.room.id==='r3').slots[0].start,15);assert.equal(r.rooms.find(x=>x.room.id==='r1').slots[0].start,13);});
check('Evento externo pendente e reserva cancelada não ocupam horário',()=>{const{data,q}=setup();data.externalReservations.push({date:q.date,roomId:'r3',status:'pendente',start:13,end:17});data.allocations.push({...q,roomId:'r3',status:'cancelada',start:13,end:17});assert.equal(search(data,q).rooms.find(x=>x.room.id==='r3').slots[0].start,13);});
check('Saldo insuficiente informa motivo e não oferece reserva',()=>{const{data,q}=setup();data.teacherSubjects.find(s=>s.id===q.disciplineId).monthlyHours=1;assert.match(search(data,q).error,/Saldo insuficiente/);});
check('Docente pesquisa somente em nome próprio e pode usar salas de todos os blocos',()=>{const{data,q}=setup();q.teacherId='t7';const r=search(data,q);assert.ok(r.rooms.length);assert.ok(r.rooms.every(x=>x.slots.every(s=>s.teacherId==='t4')));assert.deepEqual([...new Set(r.rooms.map(x=>x.room.block))].sort(),['A','B','C','D']);});
check('Coordenação e direção oferecem os mesmos ambientes para qualquer docente da unidade',()=>{const{data,q}=setup();q.teacherId='t7';q.classId='c3';q.disciplineId=data.teacherSubjects.find(s=>s.teacherId==='t7').id;const director=search(data,q,'diretor'),coordinator=search(data,q,'coordenador');assert.equal(director.error,'');assert.equal(coordinator.error,'');assert.ok(director.rooms.length);assert.equal(JSON.stringify(coordinator.rooms),JSON.stringify(director.rooms));assert.ok(coordinator.rooms.some(x=>x.room.block==='A'));assert.ok(coordinator.rooms.some(x=>x.room.block==='B'));});
check('Datas inválidas, passado, duração inválida e disciplina alheia são rejeitados',()=>{const{data,q}=setup();for(const patch of [{date:'2026-02-30'},{date:'2026-09-01'},{duration:0},{duration:5},{duration:1.1},{disciplineId:'alheia'}])assert.ok(search(data,{...q,...patch}).error);});
check('Busca do dia atual elimina horários já iniciados',()=>{const{data,q}=setup();q.date='2026-09-11';const r=find(data,M,q,'docente',new Date('2026-09-11T14:00:00-03:00'));assert.ok(r.rooms.length);assert.ok(r.rooms.every(x=>x.slots.every(s=>s.start>14)));});
function reportData(){const{data,q}=setup();data.allocations=[{id:'a1',roomId:'r1',teacherId:'t4',classId:'c3',subject:'Aula',date:q.date,areaId:'unidade',shift:'tarde',status:'confirmada',start:13,end:15},{id:'a2',roomId:'r7',teacherId:'t7',classId:'c7',date:q.date,areaId:'unidade',shift:'manha',status:'confirmada',start:8,end:10}];data.externalReservations=[{id:'e1',roomId:'r1',date:q.date,areaId:'unidade',shift:'tarde',status:'aprovada',start:14,end:16},{id:'e2',roomId:'r1',date:q.date,areaId:'unidade',shift:'tarde',status:'pendente',start:16,end:17}];return {data,f:{start:q.date,end:q.date,area:'todas'}};}
check('Detalhes da ocupação incluem externo confirmado e calculam união de intervalos',()=>{const{data,f}=reportData();const r=collect(data,M,f,'coordenador','room','r1','occupancy');assert.equal(r.records.length,2);assert.equal(r.used,3);assert.equal(r.available,12);assert.ok(r.records.some(x=>x.key==='e:e1'));});
check('Detalhes respeitam docente, turno e período dos filtros',()=>{const{data,f}=reportData();assert.equal(collect(data,M,{...f,teacher:'t4'},'coordenador','room','r1','occupancy').records.length,1);assert.equal(collect(data,M,{...f,shift:'manha'},'coordenador','room','r1','occupancy').records.length,0);assert.equal(collect(data,M,{start:'2026-10-06',end:'2026-10-06'},'coordenador','room','r1','occupancy').records.length,0);});
check('Detalhes por turno contam apenas aulas e não alteram o filtro original',()=>{const{data,f}=reportData();const original=JSON.stringify(f);const r=collect(data,M,f,'diretor','shift','tarde','lessons','A');assert.equal(r.records.length,1);assert.equal(r.used,2);assert.equal(JSON.stringify(f),original);});
check('Coordenação consulta toda unidade e docente continua sem relatórios de gestão',()=>{const{data,f}=reportData();assert.equal(collect(data,M,f,'coordenador','room','r7','occupancy').records.length,1);assert.equal(collect(data,M,f,'coordenador','block','B','occupancy').records.length,1);assert.equal(collect(data,M,f,'docente','room','r1','occupancy'),null);});
check('Totais dos detalhes coincidem com as métricas dos ambientes e blocos',()=>{const{data,f}=reportData();const rows=M.roomStats(data,f);for(const room of rows){const r=collect(data,M,f,'diretor','room',room.id,'occupancy');assert.equal(r.used,room.used);assert.equal(r.available,room.available);}for(const block of ['A','B','C','D']){const r=collect(data,M,f,'diretor','block',block,'occupancy');const rooms=rows.filter(x=>x.block===block);assert.equal(r.used,M.sum(rooms,x=>x.used));assert.equal(r.available,M.sum(rooms,x=>x.available));}});
console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,total:results.length,failures:results.filter(x=>!x.pass)},null,2));
if(results.some(x=>!x.pass))process.exitCode=1;
